### ISSUE TITLE
Wakeup and touch issues with DT2W enabled

### ISSUE THREAD

**Issue by Gabriel85** [Lenovo-YTX703-Devel/android_kernel_lenovo_msm8976#6]
I readded DT2W (based on the original one by Christian and with Vlad's updates) for my extended kernel and I get two (old) issues.

1. sometimes it doesn't wake up after touching 
2. sometimes (very rarely) the screen becomes extremely unresponsive, to the point it is totally unusable. I originally thought that this was related to some recalibration issue, due to the fact that the touch sensor is kept on all the time. But this time it happened from one second to another while I was using it.
Disabling DT2W solves the issue (after you turn the screen off an on) instantly.

This is the log after the second issue (showed the same after the first one):
```
[ 3494.808041] i2c-msm-v2 78b8000.i2c: TIMEOUT_ERROR(val:510msec) misconfigured GPIO or slave pulling bus line(s) low
[ 3494.808041] : msgs(n:2 cur:0 tx) bc(rx:2 tx:1) mode:FIFO slv_addr:0x38 MSTR_STS:0x0c110000 OPER:0x00000f60
[ 3494.809277] synaptics_dsx_i2c 4-0038: synaptics_rmi4_i2c_read: I2C retry 1
[ 3494.838041] i2c-msm-v2 78b8000.i2c: Runtime PM-callback was not invoked.
```

**Comment by vladimiroltean** [comment]
You opened an issue for some code that's not in this repo?

**Comment by Gabriel85** [comment]
You asked a question, which answer you already know? ;)

**Comment by vladimiroltean** [comment]
Software-based DT2W has no place for discussion here.
